// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: jid.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppKey         *string `protobuf:"bytes,1,opt,name=app_key,json=appKey" json:"app_key,omitempty"`
	Name           *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Domain         *string `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	ClientResource *string `protobuf:"bytes,4,opt,name=client_resource,json=clientResource" json:"client_resource,omitempty"`
}

func (x *JID) Reset() {
	*x = JID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JID) ProtoMessage() {}

func (x *JID) ProtoReflect() protoreflect.Message {
	mi := &file_jid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JID.ProtoReflect.Descriptor instead.
func (*JID) Descriptor() ([]byte, []int) {
	return file_jid_proto_rawDescGZIP(), []int{0}
}

func (x *JID) GetAppKey() string {
	if x != nil && x.AppKey != nil {
		return *x.AppKey
	}
	return ""
}

func (x *JID) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *JID) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *JID) GetClientResource() string {
	if x != nil && x.ClientResource != nil {
		return *x.ClientResource
	}
	return ""
}

var File_jid_proto protoreflect.FileDescriptor

var file_jid_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6a, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x61, 0x73,
	0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x22, 0x73, 0x0a, 0x03, 0x4a, 0x49, 0x44, 0x12, 0x17,
	0x0a, 0x07, 0x61, 0x70, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x02, 0x48, 0x03,
}

var (
	file_jid_proto_rawDescOnce sync.Once
	file_jid_proto_rawDescData = file_jid_proto_rawDesc
)

func file_jid_proto_rawDescGZIP() []byte {
	file_jid_proto_rawDescOnce.Do(func() {
		file_jid_proto_rawDescData = protoimpl.X.CompressGZIP(file_jid_proto_rawDescData)
	})
	return file_jid_proto_rawDescData
}

var file_jid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jid_proto_goTypes = []interface{}{
	(*JID)(nil), // 0: easemob.pb.JID
}
var file_jid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jid_proto_init() }
func file_jid_proto_init() {
	if File_jid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jid_proto_goTypes,
		DependencyIndexes: file_jid_proto_depIdxs,
		MessageInfos:      file_jid_proto_msgTypes,
	}.Build()
	File_jid_proto = out.File
	file_jid_proto_rawDesc = nil
	file_jid_proto_goTypes = nil
	file_jid_proto_depIdxs = nil
}
