// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: keyvalue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyValue_ValueType int32

const (
	KeyValue_BOOL        KeyValue_ValueType = 1
	KeyValue_INT         KeyValue_ValueType = 2
	KeyValue_UINT        KeyValue_ValueType = 3
	KeyValue_LLINT       KeyValue_ValueType = 4
	KeyValue_FLOAT       KeyValue_ValueType = 5
	KeyValue_DOUBLE      KeyValue_ValueType = 6
	KeyValue_STRING      KeyValue_ValueType = 7
	KeyValue_JSON_STRING KeyValue_ValueType = 8
)

// Enum value maps for KeyValue_ValueType.
var (
	KeyValue_ValueType_name = map[int32]string{
		1: "BOOL",
		2: "INT",
		3: "UINT",
		4: "LLINT",
		5: "FLOAT",
		6: "DOUBLE",
		7: "STRING",
		8: "JSON_STRING",
	}
	KeyValue_ValueType_value = map[string]int32{
		"BOOL":        1,
		"INT":         2,
		"UINT":        3,
		"LLINT":       4,
		"FLOAT":       5,
		"DOUBLE":      6,
		"STRING":      7,
		"JSON_STRING": 8,
	}
)

func (x KeyValue_ValueType) Enum() *KeyValue_ValueType {
	p := new(KeyValue_ValueType)
	*p = x
	return p
}

func (x KeyValue_ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyValue_ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_keyvalue_proto_enumTypes[0].Descriptor()
}

func (KeyValue_ValueType) Type() protoreflect.EnumType {
	return &file_keyvalue_proto_enumTypes[0]
}

func (x KeyValue_ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *KeyValue_ValueType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = KeyValue_ValueType(num)
	return nil
}

// Deprecated: Use KeyValue_ValueType.Descriptor instead.
func (KeyValue_ValueType) EnumDescriptor() ([]byte, []int) {
	return file_keyvalue_proto_rawDescGZIP(), []int{0, 0}
}

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  *string             `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Type *KeyValue_ValueType `protobuf:"varint,2,opt,name=type,enum=easemob.pb.KeyValue_ValueType" json:"type,omitempty"`
	// Types that are assignable to Value:
	//	*KeyValue_VarintValue
	//	*KeyValue_FloatValue
	//	*KeyValue_DoubleValue
	//	*KeyValue_StringValue
	Value isKeyValue_Value `protobuf_oneof:"value"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keyvalue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_keyvalue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_keyvalue_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *KeyValue) GetType() KeyValue_ValueType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return KeyValue_BOOL
}

func (m *KeyValue) GetValue() isKeyValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *KeyValue) GetVarintValue() int64 {
	if x, ok := x.GetValue().(*KeyValue_VarintValue); ok {
		return x.VarintValue
	}
	return 0
}

func (x *KeyValue) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*KeyValue_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *KeyValue) GetDoubleValue() float64 {
	if x, ok := x.GetValue().(*KeyValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *KeyValue) GetStringValue() string {
	if x, ok := x.GetValue().(*KeyValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

type isKeyValue_Value interface {
	isKeyValue_Value()
}

type KeyValue_VarintValue struct {
	VarintValue int64 `protobuf:"varint,3,opt,name=varint_value,json=varintValue,oneof"`
}

type KeyValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,oneof"`
}

type KeyValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,oneof"`
}

type KeyValue_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,oneof"`
}

func (*KeyValue_VarintValue) isKeyValue_Value() {}

func (*KeyValue_FloatValue) isKeyValue_Value() {}

func (*KeyValue_DoubleValue) isKeyValue_Value() {}

func (*KeyValue_StringValue) isKeyValue_Value() {}

var File_keyvalue_proto protoreflect.FileDescriptor

var file_keyvalue_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x22, 0xd4, 0x02, 0x0a,
	0x08, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x65, 0x61, 0x73, 0x65,
	0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x23, 0x0a, 0x0c, 0x76, 0x61, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0b, 0x76, 0x61, 0x72, 0x69, 0x6e, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52,
	0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x67, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x49, 0x4e, 0x54, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4c,
	0x4c, 0x49, 0x4e, 0x54, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10,
	0x05, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x10, 0x06, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x4a, 0x53, 0x4f,
	0x4e, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x08, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x02, 0x48, 0x03,
}

var (
	file_keyvalue_proto_rawDescOnce sync.Once
	file_keyvalue_proto_rawDescData = file_keyvalue_proto_rawDesc
)

func file_keyvalue_proto_rawDescGZIP() []byte {
	file_keyvalue_proto_rawDescOnce.Do(func() {
		file_keyvalue_proto_rawDescData = protoimpl.X.CompressGZIP(file_keyvalue_proto_rawDescData)
	})
	return file_keyvalue_proto_rawDescData
}

var file_keyvalue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keyvalue_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_keyvalue_proto_goTypes = []interface{}{
	(KeyValue_ValueType)(0), // 0: easemob.pb.KeyValue.ValueType
	(*KeyValue)(nil),        // 1: easemob.pb.KeyValue
}
var file_keyvalue_proto_depIdxs = []int32{
	0, // 0: easemob.pb.KeyValue.type:type_name -> easemob.pb.KeyValue.ValueType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_keyvalue_proto_init() }
func file_keyvalue_proto_init() {
	if File_keyvalue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keyvalue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_keyvalue_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*KeyValue_VarintValue)(nil),
		(*KeyValue_FloatValue)(nil),
		(*KeyValue_DoubleValue)(nil),
		(*KeyValue_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keyvalue_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keyvalue_proto_goTypes,
		DependencyIndexes: file_keyvalue_proto_depIdxs,
		EnumInfos:         file_keyvalue_proto_enumTypes,
		MessageInfos:      file_keyvalue_proto_msgTypes,
	}.Build()
	File_keyvalue_proto = out.File
	file_keyvalue_proto_rawDesc = nil
	file_keyvalue_proto_goTypes = nil
	file_keyvalue_proto_depIdxs = nil
}
