// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: msync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptType int32

const (
	EncryptType_ENCRYPT_NONE        EncryptType = 0
	EncryptType_ENCRYPT_AES_128_CBC EncryptType = 1 //default encryption type.
	EncryptType_ENCRYPT_AES_256_CBC EncryptType = 2 //
	EncryptType_ENCRYPT_AES_GCM     EncryptType = 3
)

// Enum value maps for EncryptType.
var (
	EncryptType_name = map[int32]string{
		0: "ENCRYPT_NONE",
		1: "ENCRYPT_AES_128_CBC",
		2: "ENCRYPT_AES_256_CBC",
		3: "ENCRYPT_AES_GCM",
	}
	EncryptType_value = map[string]int32{
		"ENCRYPT_NONE":        0,
		"ENCRYPT_AES_128_CBC": 1,
		"ENCRYPT_AES_256_CBC": 2,
		"ENCRYPT_AES_GCM":     3,
	}
)

func (x EncryptType) Enum() *EncryptType {
	p := new(EncryptType)
	*p = x
	return p
}

func (x EncryptType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptType) Descriptor() protoreflect.EnumDescriptor {
	return file_msync_proto_enumTypes[0].Descriptor()
}

func (EncryptType) Type() protoreflect.EnumType {
	return &file_msync_proto_enumTypes[0]
}

func (x EncryptType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EncryptType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EncryptType(num)
	return nil
}

// Deprecated: Use EncryptType.Descriptor instead.
func (EncryptType) EnumDescriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{0}
}

type MSync_Version int32

const (
	MSync_MSYNC_V1 MSync_Version = 0
	MSync_MSYNC_V2 MSync_Version = 1
)

// Enum value maps for MSync_Version.
var (
	MSync_Version_name = map[int32]string{
		0: "MSYNC_V1",
		1: "MSYNC_V2",
	}
	MSync_Version_value = map[string]int32{
		"MSYNC_V1": 0,
		"MSYNC_V2": 1,
	}
)

func (x MSync_Version) Enum() *MSync_Version {
	p := new(MSync_Version)
	*p = x
	return p
}

func (x MSync_Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSync_Version) Descriptor() protoreflect.EnumDescriptor {
	return file_msync_proto_enumTypes[1].Descriptor()
}

func (MSync_Version) Type() protoreflect.EnumType {
	return &file_msync_proto_enumTypes[1]
}

func (x MSync_Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MSync_Version) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MSync_Version(num)
	return nil
}

// Deprecated: Use MSync_Version.Descriptor instead.
func (MSync_Version) EnumDescriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{0, 0}
}

type MSync_Command int32

const (
	MSync_SYNC      MSync_Command = 0
	MSync_UNREAD    MSync_Command = 1
	MSync_NOTICE    MSync_Command = 2
	MSync_PROVISION MSync_Command = 3
	MSync_LOGOUT    MSync_Command = 4 //logout 交互信令
)

// Enum value maps for MSync_Command.
var (
	MSync_Command_name = map[int32]string{
		0: "SYNC",
		1: "UNREAD",
		2: "NOTICE",
		3: "PROVISION",
		4: "LOGOUT",
	}
	MSync_Command_value = map[string]int32{
		"SYNC":      0,
		"UNREAD":    1,
		"NOTICE":    2,
		"PROVISION": 3,
		"LOGOUT":    4,
	}
)

func (x MSync_Command) Enum() *MSync_Command {
	p := new(MSync_Command)
	*p = x
	return p
}

func (x MSync_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSync_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_msync_proto_enumTypes[2].Descriptor()
}

func (MSync_Command) Type() protoreflect.EnumType {
	return &file_msync_proto_enumTypes[2]
}

func (x MSync_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MSync_Command) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MSync_Command(num)
	return nil
}

// Deprecated: Use MSync_Command.Descriptor instead.
func (MSync_Command) EnumDescriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{0, 1}
}

type Meta_NameSpace int32

const (
	Meta_STATISTIC  Meta_NameSpace = 0
	Meta_CHAT       Meta_NameSpace = 1
	Meta_MUC        Meta_NameSpace = 2
	Meta_ROSTER     Meta_NameSpace = 3 // ROSTER ops
	Meta_CONFERENCE Meta_NameSpace = 4 // realtime calling
	Meta_NOTIFY     Meta_NameSpace = 5 //  notify from server, payload is json
	Meta_QUERY      Meta_NameSpace = 6 //  query from sdk, paydload is json
)

// Enum value maps for Meta_NameSpace.
var (
	Meta_NameSpace_name = map[int32]string{
		0: "STATISTIC",
		1: "CHAT",
		2: "MUC",
		3: "ROSTER",
		4: "CONFERENCE",
		5: "NOTIFY",
		6: "QUERY",
	}
	Meta_NameSpace_value = map[string]int32{
		"STATISTIC":  0,
		"CHAT":       1,
		"MUC":        2,
		"ROSTER":     3,
		"CONFERENCE": 4,
		"NOTIFY":     5,
		"QUERY":      6,
	}
)

func (x Meta_NameSpace) Enum() *Meta_NameSpace {
	p := new(Meta_NameSpace)
	*p = x
	return p
}

func (x Meta_NameSpace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Meta_NameSpace) Descriptor() protoreflect.EnumDescriptor {
	return file_msync_proto_enumTypes[3].Descriptor()
}

func (Meta_NameSpace) Type() protoreflect.EnumType {
	return &file_msync_proto_enumTypes[3]
}

func (x Meta_NameSpace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Meta_NameSpace) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Meta_NameSpace(num)
	return nil
}

// Deprecated: Use Meta_NameSpace.Descriptor instead.
func (Meta_NameSpace) EnumDescriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{8, 0}
}

type Meta_RouteType int32

const (
	Meta_ROUTE_ALL    Meta_RouteType = 0
	Meta_ROUTE_ONLINE Meta_RouteType = 1 //just send messages to online users
	Meta_ROUTE_DIRECT Meta_RouteType = 2 // send group/room message to special users
)

// Enum value maps for Meta_RouteType.
var (
	Meta_RouteType_name = map[int32]string{
		0: "ROUTE_ALL",
		1: "ROUTE_ONLINE",
		2: "ROUTE_DIRECT",
	}
	Meta_RouteType_value = map[string]int32{
		"ROUTE_ALL":    0,
		"ROUTE_ONLINE": 1,
		"ROUTE_DIRECT": 2,
	}
)

func (x Meta_RouteType) Enum() *Meta_RouteType {
	p := new(Meta_RouteType)
	*p = x
	return p
}

func (x Meta_RouteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Meta_RouteType) Descriptor() protoreflect.EnumDescriptor {
	return file_msync_proto_enumTypes[4].Descriptor()
}

func (Meta_RouteType) Type() protoreflect.EnumType {
	return &file_msync_proto_enumTypes[4]
}

func (x Meta_RouteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Meta_RouteType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Meta_RouteType(num)
	return nil
}

// Deprecated: Use Meta_RouteType.Descriptor instead.
func (Meta_RouteType) EnumDescriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{8, 1}
}

type Status_ErrorCode int32

const (
	Status_OK                         Status_ErrorCode = 0
	Status_FAIL                       Status_ErrorCode = 1
	Status_UNAUTHORIZED               Status_ErrorCode = 2
	Status_MISSING_PARAMETER          Status_ErrorCode = 3
	Status_WRONG_PARAMETER            Status_ErrorCode = 4
	Status_REDIRECT                   Status_ErrorCode = 5
	Status_TOKEN_EXPIRED              Status_ErrorCode = 6
	Status_PERMISSION_DENIED          Status_ErrorCode = 7 // if user in blacklist
	Status_NO_ROUTE                   Status_ErrorCode = 8 // for multi IDC, or wrong user domain
	Status_UNKNOWN_COMMAND            Status_ErrorCode = 9
	Status_PB_PARSER_ERROR            Status_ErrorCode = 10 // for protobuf parser error
	Status_BIND_ANOTHER_DEVICE        Status_ErrorCode = 11 // user already login on another device manually
	Status_IM_FORBIDDEN               Status_ErrorCode = 12 // user is forbidden to login
	Status_TOO_MANY_DEVICES           Status_ErrorCode = 13 // user login exceed the limitation of device number
	Status_PLATFORM_LIMIT             Status_ErrorCode = 14 // for limit user login without opening platform
	Status_USER_MUTED                 Status_ErrorCode = 15 // user is muted in group
	Status_ENCRYPT_DISABLE            Status_ErrorCode = 16 // encryption disable.
	Status_ENCRYPT_ENABLE             Status_ErrorCode = 17 // use encryption.
	Status_DECRYPT_FAILURE            Status_ErrorCode = 18 // decryption failure.
	Status_PERMISSION_DENIED_EXTERNAL Status_ErrorCode = 19 // blocked by external logic.
	Status_RESOURCE_CHANGED           Status_ErrorCode = 20 // user login changed resource.
)

// Enum value maps for Status_ErrorCode.
var (
	Status_ErrorCode_name = map[int32]string{
		0:  "OK",
		1:  "FAIL",
		2:  "UNAUTHORIZED",
		3:  "MISSING_PARAMETER",
		4:  "WRONG_PARAMETER",
		5:  "REDIRECT",
		6:  "TOKEN_EXPIRED",
		7:  "PERMISSION_DENIED",
		8:  "NO_ROUTE",
		9:  "UNKNOWN_COMMAND",
		10: "PB_PARSER_ERROR",
		11: "BIND_ANOTHER_DEVICE",
		12: "IM_FORBIDDEN",
		13: "TOO_MANY_DEVICES",
		14: "PLATFORM_LIMIT",
		15: "USER_MUTED",
		16: "ENCRYPT_DISABLE",
		17: "ENCRYPT_ENABLE",
		18: "DECRYPT_FAILURE",
		19: "PERMISSION_DENIED_EXTERNAL",
		20: "RESOURCE_CHANGED",
	}
	Status_ErrorCode_value = map[string]int32{
		"OK":                         0,
		"FAIL":                       1,
		"UNAUTHORIZED":               2,
		"MISSING_PARAMETER":          3,
		"WRONG_PARAMETER":            4,
		"REDIRECT":                   5,
		"TOKEN_EXPIRED":              6,
		"PERMISSION_DENIED":          7,
		"NO_ROUTE":                   8,
		"UNKNOWN_COMMAND":            9,
		"PB_PARSER_ERROR":            10,
		"BIND_ANOTHER_DEVICE":        11,
		"IM_FORBIDDEN":               12,
		"TOO_MANY_DEVICES":           13,
		"PLATFORM_LIMIT":             14,
		"USER_MUTED":                 15,
		"ENCRYPT_DISABLE":            16,
		"ENCRYPT_ENABLE":             17,
		"DECRYPT_FAILURE":            18,
		"PERMISSION_DENIED_EXTERNAL": 19,
		"RESOURCE_CHANGED":           20,
	}
)

func (x Status_ErrorCode) Enum() *Status_ErrorCode {
	p := new(Status_ErrorCode)
	*p = x
	return p
}

func (x Status_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_msync_proto_enumTypes[5].Descriptor()
}

func (Status_ErrorCode) Type() protoreflect.EnumType {
	return &file_msync_proto_enumTypes[5]
}

func (x Status_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Status_ErrorCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Status_ErrorCode(num)
	return nil
}

// Deprecated: Use Status_ErrorCode.Descriptor instead.
func (Status_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{9, 0}
}

type Provision_OsType int32

const (
	Provision_OS_IOS     Provision_OsType = 0
	Provision_OS_ANDROID Provision_OsType = 1
	Provision_OS_LINUX   Provision_OsType = 2
	Provision_OS_OSX     Provision_OsType = 3
	Provision_OS_WIN     Provision_OsType = 4
	Provision_OS_CUSTOM  Provision_OsType = 5
	Provision_OS_HARMONY Provision_OsType = 6
	Provision_OS_GO      Provision_OsType = 7
	Provision_OS_OTHER   Provision_OsType = 16
)

// Enum value maps for Provision_OsType.
var (
	Provision_OsType_name = map[int32]string{
		0:  "OS_IOS",
		1:  "OS_ANDROID",
		2:  "OS_LINUX",
		3:  "OS_OSX",
		4:  "OS_WIN",
		5:  "OS_CUSTOM",
		6:  "OS_HARMONY",
		7:  "OS_GO",
		16: "OS_OTHER",
	}
	Provision_OsType_value = map[string]int32{
		"OS_IOS":     0,
		"OS_ANDROID": 1,
		"OS_LINUX":   2,
		"OS_OSX":     3,
		"OS_WIN":     4,
		"OS_CUSTOM":  5,
		"OS_HARMONY": 6,
		"OS_GO":      7,
		"OS_OTHER":   16,
	}
)

func (x Provision_OsType) Enum() *Provision_OsType {
	p := new(Provision_OsType)
	*p = x
	return p
}

func (x Provision_OsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provision_OsType) Descriptor() protoreflect.EnumDescriptor {
	return file_msync_proto_enumTypes[6].Descriptor()
}

func (Provision_OsType) Type() protoreflect.EnumType {
	return &file_msync_proto_enumTypes[6]
}

func (x Provision_OsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Provision_OsType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Provision_OsType(num)
	return nil
}

// Deprecated: Use Provision_OsType.Descriptor instead.
func (Provision_OsType) EnumDescriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{11, 0}
}

type Provision_NetworkType int32

const (
	Provision_NETWORK_NONE Provision_NetworkType = 0
	Provision_NETWORK_WIFI Provision_NetworkType = 1
	Provision_NETWORK_4G   Provision_NetworkType = 2
	Provision_NETWORK_3G   Provision_NetworkType = 3
	Provision_NETWORK_2G   Provision_NetworkType = 4
	Provision_NETWORK_WIRE Provision_NetworkType = 5
)

// Enum value maps for Provision_NetworkType.
var (
	Provision_NetworkType_name = map[int32]string{
		0: "NETWORK_NONE",
		1: "NETWORK_WIFI",
		2: "NETWORK_4G",
		3: "NETWORK_3G",
		4: "NETWORK_2G",
		5: "NETWORK_WIRE",
	}
	Provision_NetworkType_value = map[string]int32{
		"NETWORK_NONE": 0,
		"NETWORK_WIFI": 1,
		"NETWORK_4G":   2,
		"NETWORK_3G":   3,
		"NETWORK_2G":   4,
		"NETWORK_WIRE": 5,
	}
)

func (x Provision_NetworkType) Enum() *Provision_NetworkType {
	p := new(Provision_NetworkType)
	*p = x
	return p
}

func (x Provision_NetworkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provision_NetworkType) Descriptor() protoreflect.EnumDescriptor {
	return file_msync_proto_enumTypes[7].Descriptor()
}

func (Provision_NetworkType) Type() protoreflect.EnumType {
	return &file_msync_proto_enumTypes[7]
}

func (x Provision_NetworkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Provision_NetworkType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Provision_NetworkType(num)
	return nil
}

// Deprecated: Use Provision_NetworkType.Descriptor instead.
func (Provision_NetworkType) EnumDescriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{11, 1}
}

type Provision_CompressType int32

const (
	Provision_COMPRESS_NONE Provision_CompressType = 0
	Provision_COMPRESS_ZLIB Provision_CompressType = 1
	Provision_COMPRESS_LZ4  Provision_CompressType = 2 // 新增 lz4流式压缩
)

// Enum value maps for Provision_CompressType.
var (
	Provision_CompressType_name = map[int32]string{
		0: "COMPRESS_NONE",
		1: "COMPRESS_ZLIB",
		2: "COMPRESS_LZ4",
	}
	Provision_CompressType_value = map[string]int32{
		"COMPRESS_NONE": 0,
		"COMPRESS_ZLIB": 1,
		"COMPRESS_LZ4":  2,
	}
)

func (x Provision_CompressType) Enum() *Provision_CompressType {
	p := new(Provision_CompressType)
	*p = x
	return p
}

func (x Provision_CompressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provision_CompressType) Descriptor() protoreflect.EnumDescriptor {
	return file_msync_proto_enumTypes[8].Descriptor()
}

func (Provision_CompressType) Type() protoreflect.EnumType {
	return &file_msync_proto_enumTypes[8]
}

func (x Provision_CompressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Provision_CompressType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Provision_CompressType(num)
	return nil
}

// Deprecated: Use Provision_CompressType.Descriptor instead.
func (Provision_CompressType) EnumDescriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{11, 2}
}

type Provision_CompressDirection int32

const (
	Provision_ONLY_UP   Provision_CompressDirection = 0 // 仅上行压缩
	Provision_ONLY_DOWN Provision_CompressDirection = 1 // 仅下行压缩
	Provision_BI        Provision_CompressDirection = 2 // 双向压缩
)

// Enum value maps for Provision_CompressDirection.
var (
	Provision_CompressDirection_name = map[int32]string{
		0: "ONLY_UP",
		1: "ONLY_DOWN",
		2: "BI",
	}
	Provision_CompressDirection_value = map[string]int32{
		"ONLY_UP":   0,
		"ONLY_DOWN": 1,
		"BI":        2,
	}
)

func (x Provision_CompressDirection) Enum() *Provision_CompressDirection {
	p := new(Provision_CompressDirection)
	*p = x
	return p
}

func (x Provision_CompressDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provision_CompressDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_msync_proto_enumTypes[9].Descriptor()
}

func (Provision_CompressDirection) Type() protoreflect.EnumType {
	return &file_msync_proto_enumTypes[9]
}

func (x Provision_CompressDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Provision_CompressDirection) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Provision_CompressDirection(num)
	return nil
}

// Deprecated: Use Provision_CompressDirection.Descriptor instead.
func (Provision_CompressDirection) EnumDescriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{11, 3}
}

type MSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version           *MSync_Version `protobuf:"varint,1,opt,name=version,enum=easemob.pb.MSync_Version,def=0" json:"version,omitempty"`
	Guid              *JID           `protobuf:"bytes,2,opt,name=guid" json:"guid,omitempty"`
	Auth              *string        `protobuf:"bytes,3,opt,name=auth" json:"auth,omitempty"`
	CompressAlgorimth *uint32        `protobuf:"varint,4,opt,name=compress_algorimth,json=compressAlgorimth" json:"compress_algorimth,omitempty"`
	Crypto            *uint32        `protobuf:"varint,5,opt,name=crypto" json:"crypto,omitempty"`
	UserAgent         *string        `protobuf:"bytes,6,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Pov               *uint64        `protobuf:"varint,7,opt,name=pov" json:"pov,omitempty"`
	Command           *MSync_Command `protobuf:"varint,8,opt,name=command,enum=easemob.pb.MSync_Command" json:"command,omitempty"`
	DeviceId          *uint32        `protobuf:"varint,10,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	EncryptType       []EncryptType  `protobuf:"varint,11,rep,name=encrypt_type,json=encryptType,enum=easemob.pb.EncryptType" json:"encrypt_type,omitempty"` //encrypt type.
	EncryptKey        *string        `protobuf:"bytes,12,opt,name=encrypt_key,json=encryptKey" json:"encrypt_key,omitempty"`                                 //encrypted symmetric key.
	Tag               []byte         `protobuf:"bytes,13,opt,name=tag" json:"tag,omitempty"`                                                                 //aes_gcm tag
	Iv                []byte         `protobuf:"bytes,14,opt,name=iv" json:"iv,omitempty"`                                                                   //aes_gcm iv
	// It could be one of CommSyncUL, CommSyncDL, CommUnreadUL, CommUnreadDL, or CommNotice.
	// It is compressed if compress_algorimth is not zero.
	Payload []byte  `protobuf:"bytes,9,opt,name=payload" json:"payload,omitempty"`
	TraceId *uint64 `protobuf:"varint,20,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"` //The unique id trace to request.
}

// Default values for MSync fields.
const (
	Default_MSync_Version = MSync_MSYNC_V1
)

func (x *MSync) Reset() {
	*x = MSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSync) ProtoMessage() {}

func (x *MSync) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSync.ProtoReflect.Descriptor instead.
func (*MSync) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{0}
}

func (x *MSync) GetVersion() MSync_Version {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return Default_MSync_Version
}

func (x *MSync) GetGuid() *JID {
	if x != nil {
		return x.Guid
	}
	return nil
}

func (x *MSync) GetAuth() string {
	if x != nil && x.Auth != nil {
		return *x.Auth
	}
	return ""
}

func (x *MSync) GetCompressAlgorimth() uint32 {
	if x != nil && x.CompressAlgorimth != nil {
		return *x.CompressAlgorimth
	}
	return 0
}

func (x *MSync) GetCrypto() uint32 {
	if x != nil && x.Crypto != nil {
		return *x.Crypto
	}
	return 0
}

func (x *MSync) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *MSync) GetPov() uint64 {
	if x != nil && x.Pov != nil {
		return *x.Pov
	}
	return 0
}

func (x *MSync) GetCommand() MSync_Command {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return MSync_SYNC
}

func (x *MSync) GetDeviceId() uint32 {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return 0
}

func (x *MSync) GetEncryptType() []EncryptType {
	if x != nil {
		return x.EncryptType
	}
	return nil
}

func (x *MSync) GetEncryptKey() string {
	if x != nil && x.EncryptKey != nil {
		return *x.EncryptKey
	}
	return ""
}

func (x *MSync) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *MSync) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *MSync) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MSync) GetTraceId() uint64 {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return 0
}

type CommSyncUL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// for client to send meta to server
	Meta *Meta `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"` // not "repeated", UL send one meta every time.
	// for server to send meta to client
	Key             *uint64     `protobuf:"varint,2,opt,name=key" json:"key,omitempty"`
	Queue           *JID        `protobuf:"bytes,3,opt,name=queue" json:"queue,omitempty"`
	IsRoam          *bool       `protobuf:"varint,4,opt,name=is_roam,json=isRoam" json:"is_roam,omitempty"`
	LastFullRoamKey *uint64     `protobuf:"varint,5,opt,name=last_full_roam_key,json=lastFullRoamKey" json:"last_full_roam_key,omitempty"`
	RoamConfig      *RoamConfig `protobuf:"bytes,6,opt,name=roam_config,json=roamConfig" json:"roam_config,omitempty"`
}

func (x *CommSyncUL) Reset() {
	*x = CommSyncUL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommSyncUL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommSyncUL) ProtoMessage() {}

func (x *CommSyncUL) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommSyncUL.ProtoReflect.Descriptor instead.
func (*CommSyncUL) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{1}
}

func (x *CommSyncUL) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CommSyncUL) GetKey() uint64 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *CommSyncUL) GetQueue() *JID {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *CommSyncUL) GetIsRoam() bool {
	if x != nil && x.IsRoam != nil {
		return *x.IsRoam
	}
	return false
}

func (x *CommSyncUL) GetLastFullRoamKey() uint64 {
	if x != nil && x.LastFullRoamKey != nil {
		return *x.LastFullRoamKey
	}
	return 0
}

func (x *CommSyncUL) GetRoamConfig() *RoamConfig {
	if x != nil {
		return x.RoamConfig
	}
	return nil
}

type RoamConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsPositive *bool   `protobuf:"varint,1,opt,name=is_positive,json=isPositive" json:"is_positive,omitempty"` //是否选择正向拉取漫游（从最老向最新拉取），默认是false
	PullNumber *uint64 `protobuf:"varint,2,opt,name=pull_number,json=pullNumber" json:"pull_number,omitempty"` //单次漫游拉取数量，如果没有设置，会按照服务端默认设置50来拉取。
}

func (x *RoamConfig) Reset() {
	*x = RoamConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoamConfig) ProtoMessage() {}

func (x *RoamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoamConfig.ProtoReflect.Descriptor instead.
func (*RoamConfig) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{2}
}

func (x *RoamConfig) GetIsPositive() bool {
	if x != nil && x.IsPositive != nil {
		return *x.IsPositive
	}
	return false
}

func (x *RoamConfig) GetPullNumber() uint64 {
	if x != nil && x.PullNumber != nil {
		return *x.PullNumber
	}
	return 0
}

type CommSyncDL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// for client to send meta to server
	Status   *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	MetaId   *uint64 `protobuf:"varint,2,opt,name=meta_id,json=metaId" json:"meta_id,omitempty"`
	ServerId *uint64 `protobuf:"varint,3,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	// for server send meta to client
	Metas     []*Meta `protobuf:"bytes,4,rep,name=metas" json:"metas,omitempty"`
	NextKey   *uint64 `protobuf:"varint,5,opt,name=next_key,json=nextKey" json:"next_key,omitempty"`
	Queue     *JID    `protobuf:"bytes,6,opt,name=queue" json:"queue,omitempty"`
	IsLast    *bool   `protobuf:"varint,7,opt,name=is_last,json=isLast" json:"is_last,omitempty"`
	Timestamp *uint64 `protobuf:"varint,8,opt,name=timestamp" json:"timestamp,omitempty"` // in milli_seconds, server time.
	IsRoam    *bool   `protobuf:"varint,9,opt,name=is_roam,json=isRoam" json:"is_roam,omitempty"`
}

func (x *CommSyncDL) Reset() {
	*x = CommSyncDL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommSyncDL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommSyncDL) ProtoMessage() {}

func (x *CommSyncDL) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommSyncDL.ProtoReflect.Descriptor instead.
func (*CommSyncDL) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{3}
}

func (x *CommSyncDL) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CommSyncDL) GetMetaId() uint64 {
	if x != nil && x.MetaId != nil {
		return *x.MetaId
	}
	return 0
}

func (x *CommSyncDL) GetServerId() uint64 {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return 0
}

func (x *CommSyncDL) GetMetas() []*Meta {
	if x != nil {
		return x.Metas
	}
	return nil
}

func (x *CommSyncDL) GetNextKey() uint64 {
	if x != nil && x.NextKey != nil {
		return *x.NextKey
	}
	return 0
}

func (x *CommSyncDL) GetQueue() *JID {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *CommSyncDL) GetIsLast() bool {
	if x != nil && x.IsLast != nil {
		return *x.IsLast
	}
	return false
}

func (x *CommSyncDL) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *CommSyncDL) GetIsRoam() bool {
	if x != nil && x.IsRoam != nil {
		return *x.IsRoam
	}
	return false
}

type CommNotice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queue *JID `protobuf:"bytes,1,opt,name=queue" json:"queue,omitempty"`
}

func (x *CommNotice) Reset() {
	*x = CommNotice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommNotice) ProtoMessage() {}

func (x *CommNotice) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommNotice.ProtoReflect.Descriptor instead.
func (*CommNotice) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{4}
}

func (x *CommNotice) GetQueue() *JID {
	if x != nil {
		return x.Queue
	}
	return nil
}

type CommUnreadUL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommUnreadUL) Reset() {
	*x = CommUnreadUL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommUnreadUL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommUnreadUL) ProtoMessage() {}

func (x *CommUnreadUL) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommUnreadUL.ProtoReflect.Descriptor instead.
func (*CommUnreadUL) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{5}
}

type CommUnreadDL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *Status      `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Unread    []*MetaQueue `protobuf:"bytes,2,rep,name=unread" json:"unread,omitempty"`
	Timestamp *uint64      `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"` // in milli_seconds, server time.
}

func (x *CommUnreadDL) Reset() {
	*x = CommUnreadDL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommUnreadDL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommUnreadDL) ProtoMessage() {}

func (x *CommUnreadDL) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommUnreadDL.ProtoReflect.Descriptor instead.
func (*CommUnreadDL) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{6}
}

func (x *CommUnreadDL) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CommUnreadDL) GetUnread() []*MetaQueue {
	if x != nil {
		return x.Unread
	}
	return nil
}

func (x *CommUnreadDL) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type MetaQueue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// system meta queue is identified by easemob.com which have no user name.
	Queue *JID    `protobuf:"bytes,1,opt,name=queue" json:"queue,omitempty"`
	N     *uint32 `protobuf:"varint,2,opt,name=n" json:"n,omitempty"`
}

func (x *MetaQueue) Reset() {
	*x = MetaQueue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaQueue) ProtoMessage() {}

func (x *MetaQueue) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaQueue.ProtoReflect.Descriptor instead.
func (*MetaQueue) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{7}
}

func (x *MetaQueue) GetQueue() *JID {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *MetaQueue) GetN() uint32 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             *uint64         `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	From           *JID            `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`            // if appkey is absent, it assumes to be as same as the `guid`.
	To             *JID            `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`                // if appkey is absent, it assumes to be as same as the `from`
	Timestamp      *uint64         `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"` // in milli_seconds, server gerenated.
	Ns             *Meta_NameSpace `protobuf:"varint,5,opt,name=ns,enum=easemob.pb.Meta_NameSpace" json:"ns,omitempty"`
	Payload        []byte          `protobuf:"bytes,6,opt,name=payload" json:"payload,omitempty"`                                     // put different body to payload accoring different namespace
	Routetype      *Meta_RouteType `protobuf:"varint,7,opt,name=routetype,enum=easemob.pb.Meta_RouteType" json:"routetype,omitempty"` // route messages to users by different rules
	Ext            []*KeyValue     `protobuf:"bytes,8,rep,name=ext" json:"ext,omitempty"`                                             //chatroom message priority
	Meta           []byte          `protobuf:"bytes,9,opt,name=meta" json:"meta,omitempty"`
	DirectedUsers  []string        `protobuf:"bytes,10,rep,name=directed_users,json=directedUsers" json:"directed_users,omitempty"`     //userIds to receive message in group/room chat
	ExpireTime     *uint64         `protobuf:"varint,11,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`             //server used only, for pin message expire time
	LocalTimestamp *uint64         `protobuf:"varint,12,opt,name=local_timestamp,json=localTimestamp" json:"local_timestamp,omitempty"` // client local system timestamp in milliseconds
	Env            *string         `protobuf:"bytes,13,opt,name=env" json:"env,omitempty"`                                              // environment for callback routing
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{8}
}

func (x *Meta) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Meta) GetFrom() *JID {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Meta) GetTo() *JID {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Meta) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Meta) GetNs() Meta_NameSpace {
	if x != nil && x.Ns != nil {
		return *x.Ns
	}
	return Meta_STATISTIC
}

func (x *Meta) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Meta) GetRoutetype() Meta_RouteType {
	if x != nil && x.Routetype != nil {
		return *x.Routetype
	}
	return Meta_ROUTE_ALL
}

func (x *Meta) GetExt() []*KeyValue {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *Meta) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Meta) GetDirectedUsers() []string {
	if x != nil {
		return x.DirectedUsers
	}
	return nil
}

func (x *Meta) GetExpireTime() uint64 {
	if x != nil && x.ExpireTime != nil {
		return *x.ExpireTime
	}
	return 0
}

func (x *Meta) GetLocalTimestamp() uint64 {
	if x != nil && x.LocalTimestamp != nil {
		return *x.LocalTimestamp
	}
	return 0
}

func (x *Meta) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode    *Status_ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,enum=easemob.pb.Status_ErrorCode" json:"error_code,omitempty"`
	Reason       *string           `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	RedirectInfo []*RedirectInfo   `protobuf:"bytes,3,rep,name=redirect_info,json=redirectInfo" json:"redirect_info,omitempty"` // for error_code == REDIRECT
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{9}
}

func (x *Status) GetErrorCode() Status_ErrorCode {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return Status_OK
}

func (x *Status) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *Status) GetRedirectInfo() []*RedirectInfo {
	if x != nil {
		return x.RedirectInfo
	}
	return nil
}

type RedirectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host *string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port *uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (x *RedirectInfo) Reset() {
	*x = RedirectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedirectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectInfo) ProtoMessage() {}

func (x *RedirectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectInfo.ProtoReflect.Descriptor instead.
func (*RedirectInfo) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{10}
}

func (x *RedirectInfo) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *RedirectInfo) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

type Provision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OsType        *Provision_OsType        `protobuf:"varint,1,opt,name=os_type,json=osType,enum=easemob.pb.Provision_OsType" json:"os_type,omitempty"`
	Version       *string                  `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	NetworkType   *Provision_NetworkType   `protobuf:"varint,3,opt,name=network_type,json=networkType,enum=easemob.pb.Provision_NetworkType" json:"network_type,omitempty"`
	AppSign       *string                  `protobuf:"bytes,4,opt,name=app_sign,json=appSign" json:"app_sign,omitempty"`
	CompressType  []Provision_CompressType `protobuf:"varint,5,rep,name=compress_type,json=compressType,enum=easemob.pb.Provision_CompressType" json:"compress_type,omitempty"`
	EncryptType   []EncryptType            `protobuf:"varint,6,rep,name=encrypt_type,json=encryptType,enum=easemob.pb.EncryptType" json:"encrypt_type,omitempty"` //encrypt type.
	EncryptKey    *string                  `protobuf:"bytes,7,opt,name=encrypt_key,json=encryptKey" json:"encrypt_key,omitempty"`                                 //asymmetric public-key.
	Status        *Status                  `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`                                                           // indicate login failure etc.
	DeviceUuid    *string                  `protobuf:"bytes,9,opt,name=device_uuid,json=deviceUuid" json:"device_uuid,omitempty"`                                 // used for multi-device login
	IsManualLogin *bool                    `protobuf:"varint,10,opt,name=is_manual_login,json=isManualLogin" json:"is_manual_login,omitempty"`                    // indicate if login manually
	Password      *string                  `protobuf:"bytes,11,opt,name=password" json:"password,omitempty"`                                                      // use password to login when dns is hijacked
	DeviceName    *string                  `protobuf:"bytes,12,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`                                // device name or custom device name if have
	Resource      *string                  `protobuf:"bytes,13,opt,name=resource" json:"resource,omitempty"`                                                      // resource for bind device
	Auth          *string                  `protobuf:"bytes,14,opt,name=auth" json:"auth,omitempty"`                                                              // store login token
	AppId         *string                  `protobuf:"bytes,15,opt,name=app_id,json=appId" json:"app_id,omitempty"`                                               // user client version
	ServiceId     *string                  `protobuf:"bytes,16,opt,name=serviceId" json:"serviceId,omitempty"`                                                    // sdk serviceId
	ActionVersion *string                  `protobuf:"bytes,17,opt,name=action_version,json=actionVersion" json:"action_version,omitempty"`                       //为了避免旧版本的SDK收到新增Thread功能的影响，需要在provision协议中增加字段，告知MSync哪些SDK支持新功能
	AuthToken     []byte                   `protobuf:"bytes,18,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`                                   // style:{"vid":123,"cid":456,"token":"007"}
	OsCustomValue *uint32                  `protobuf:"varint,19,opt,name=os_custom_value,json=osCustomValue" json:"os_custom_value,omitempty"`                    //when os_type is OS_CUSTOM
	SessionId     *string                  `protobuf:"bytes,20,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`                                   //connection unique id
	Reason        *string                  `protobuf:"bytes,21,opt,name=reason" json:"reason,omitempty"`                                                          //notify other device reason
	// 对于客户端：发送协商请求，提供数组选项，可以多选
	// 对于服务器：返回协商请求结果，可以修改返回结果。返回结果：空数组、没有返回值表示不压缩，返回非空数组，使用数组元素1作为压缩算法类型
	ProtocolCompressType []Provision_CompressType `protobuf:"varint,22,rep,name=protocol_compress_type,json=protocolCompressType,enum=easemob.pb.Provision_CompressType" json:"protocol_compress_type,omitempty"`
	// 压缩方向： 默认 1
	ProtocolCompressDirection *Provision_CompressDirection `protobuf:"varint,23,opt,name=protocol_compress_direction,json=protocolCompressDirection,enum=easemob.pb.Provision_CompressDirection" json:"protocol_compress_direction,omitempty"`
	NtpKey                    []byte                       `protobuf:"bytes,24,opt,name=ntp_key,json=ntpKey" json:"ntp_key,omitempty"` // NTP 时间同步密钥，服务端在 provision reply 中下发
}

func (x *Provision) Reset() {
	*x = Provision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Provision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provision) ProtoMessage() {}

func (x *Provision) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provision.ProtoReflect.Descriptor instead.
func (*Provision) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{11}
}

func (x *Provision) GetOsType() Provision_OsType {
	if x != nil && x.OsType != nil {
		return *x.OsType
	}
	return Provision_OS_IOS
}

func (x *Provision) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Provision) GetNetworkType() Provision_NetworkType {
	if x != nil && x.NetworkType != nil {
		return *x.NetworkType
	}
	return Provision_NETWORK_NONE
}

func (x *Provision) GetAppSign() string {
	if x != nil && x.AppSign != nil {
		return *x.AppSign
	}
	return ""
}

func (x *Provision) GetCompressType() []Provision_CompressType {
	if x != nil {
		return x.CompressType
	}
	return nil
}

func (x *Provision) GetEncryptType() []EncryptType {
	if x != nil {
		return x.EncryptType
	}
	return nil
}

func (x *Provision) GetEncryptKey() string {
	if x != nil && x.EncryptKey != nil {
		return *x.EncryptKey
	}
	return ""
}

func (x *Provision) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Provision) GetDeviceUuid() string {
	if x != nil && x.DeviceUuid != nil {
		return *x.DeviceUuid
	}
	return ""
}

func (x *Provision) GetIsManualLogin() bool {
	if x != nil && x.IsManualLogin != nil {
		return *x.IsManualLogin
	}
	return false
}

func (x *Provision) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Provision) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

func (x *Provision) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *Provision) GetAuth() string {
	if x != nil && x.Auth != nil {
		return *x.Auth
	}
	return ""
}

func (x *Provision) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *Provision) GetServiceId() string {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return ""
}

func (x *Provision) GetActionVersion() string {
	if x != nil && x.ActionVersion != nil {
		return *x.ActionVersion
	}
	return ""
}

func (x *Provision) GetAuthToken() []byte {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

func (x *Provision) GetOsCustomValue() uint32 {
	if x != nil && x.OsCustomValue != nil {
		return *x.OsCustomValue
	}
	return 0
}

func (x *Provision) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *Provision) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *Provision) GetProtocolCompressType() []Provision_CompressType {
	if x != nil {
		return x.ProtocolCompressType
	}
	return nil
}

func (x *Provision) GetProtocolCompressDirection() Provision_CompressDirection {
	if x != nil && x.ProtocolCompressDirection != nil {
		return *x.ProtocolCompressDirection
	}
	return Provision_ONLY_UP
}

func (x *Provision) GetNtpKey() []byte {
	if x != nil {
		return x.NtpKey
	}
	return nil
}

type Logout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"` //connection unique id
	Reason    *string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`                        //provide logout extension message
	Status    *Status `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`                        //indicate logout success/failure etc.
}

func (x *Logout) Reset() {
	*x = Logout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msync_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logout) ProtoMessage() {}

func (x *Logout) ProtoReflect() protoreflect.Message {
	mi := &file_msync_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logout.ProtoReflect.Descriptor instead.
func (*Logout) Descriptor() ([]byte, []int) {
	return file_msync_proto_rawDescGZIP(), []int{12}
}

func (x *Logout) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *Logout) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *Logout) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_msync_proto protoreflect.FileDescriptor

var file_msync_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65,
	0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x1a, 0x09, 0x6a, 0x69, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x03, 0x0a, 0x05, 0x4d, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x34,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x53, 0x79,
	0x6e, 0x63, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3a, 0x08, 0x4d, 0x53, 0x59, 0x4e,
	0x43, 0x5f, 0x56, 0x31, 0x12, 0x1d, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e,
	0x4a, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x12, 0x1a, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x61, 0x6c,
	0x67, 0x6f, 0x72, 0x69, 0x6d, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x12, 0x0e, 0x0a,
	0x06, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x12, 0x12, 0x0a,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x12, 0x0b, 0x0a, 0x03, 0x70, 0x6f, 0x76, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x12, 0x2a,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x53, 0x79,
	0x6e, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x11, 0x0a, 0x09, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x12, 0x2d, 0x0a,
	0x0c, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20,
	0x03, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0b,
	0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x12, 0x0b, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x0a,
	0x0a, 0x02, 0x69, 0x76, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x0f, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x10, 0x0a, 0x08, 0x74,
	0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x04, 0x22, 0x25, 0x0a,
	0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x53, 0x59, 0x4e,
	0x43, 0x5f, 0x56, 0x31, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x53, 0x59, 0x4e, 0x43, 0x5f,
	0x56, 0x32, 0x10, 0x01, 0x22, 0x46, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x08, 0x0a, 0x04, 0x53, 0x59, 0x4e, 0x43, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x52,
	0x45, 0x41, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x4f, 0x47, 0x4f, 0x55, 0x54, 0x10, 0x04, 0x22, 0xb3, 0x01, 0x0a,
	0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x4c, 0x12, 0x1e, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x61, 0x73, 0x65,
	0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0b, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x12, 0x1e, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f,
	0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x49, 0x44, 0x12, 0x0f, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x72,
	0x6f, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x12, 0x1a, 0x0a, 0x12, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x6f, 0x61, 0x6d, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x12, 0x2b, 0x0a, 0x0b, 0x72, 0x6f, 0x61, 0x6d, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x61, 0x73,
	0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x22, 0x36, 0x0a, 0x0a, 0x52, 0x6f, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x13, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x12, 0x13, 0x0a, 0x0b, 0x70, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x22, 0xdc, 0x01, 0x0a, 0x0a, 0x43,
	0x6f, 0x6d, 0x6d, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x4c, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x61, 0x73, 0x65,
	0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a,
	0x07, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x12, 0x11,
	0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x12, 0x1f, 0x0a, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x12, 0x10, 0x0a, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x12, 0x1e, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62,
	0x2e, 0x4a, 0x49, 0x44, 0x12, 0x0f, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x08, 0x12, 0x11, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x12, 0x0f, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x72,
	0x6f, 0x61, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x22, 0x2c, 0x0a, 0x0a, 0x43, 0x6f, 0x6d,
	0x6d, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62,
	0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x49, 0x44, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x55,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x55, 0x4c, 0x22, 0x6c, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x55,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x44, 0x4c, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f,
	0x62, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x75,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x61,
	0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x12, 0x11, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x22, 0x36, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4a,
	0x49, 0x44, 0x12, 0x09, 0x0a, 0x01, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x22, 0xef, 0x03,
	0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0a, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x12, 0x1d, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x49,
	0x44, 0x12, 0x1b, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x49, 0x44, 0x12, 0x11,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x12, 0x26, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x2e,
	0x4e, 0x61, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0f, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x2d, 0x0a, 0x09, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x78, 0x74,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62,
	0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0c, 0x0a, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x16, 0x0a, 0x0e, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x09, 0x12, 0x13, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x12, 0x17, 0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04,
	0x12, 0x0b, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x22, 0x60, 0x0a,
	0x09, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x54,
	0x41, 0x54, 0x49, 0x53, 0x54, 0x49, 0x43, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x48, 0x41,
	0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x55, 0x43, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x52, 0x4f, 0x53, 0x54, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4e, 0x46,
	0x45, 0x52, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49,
	0x46, 0x59, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10, 0x06, 0x22,
	0x3e, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x52, 0x4f, 0x55, 0x54, 0x45, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x52,
	0x4f, 0x55, 0x54, 0x45, 0x5f, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x10, 0x02, 0x22,
	0xa2, 0x04, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x12, 0x2f, 0x0a, 0x0d,
	0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xa4, 0x03,
	0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f,
	0x4b, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x15, 0x0a, 0x11, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d,
	0x45, 0x54, 0x45, 0x52, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x57, 0x52, 0x4f, 0x4e, 0x47, 0x5f,
	0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54, 0x45, 0x52, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x52,
	0x45, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x4f, 0x4b,
	0x45, 0x4e, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11,
	0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45,
	0x44, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x10,
	0x08, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x4f, 0x4d,
	0x4d, 0x41, 0x4e, 0x44, 0x10, 0x09, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x42, 0x5f, 0x50, 0x41, 0x52,
	0x53, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x0a, 0x12, 0x17, 0x0a, 0x13, 0x42,
	0x49, 0x4e, 0x44, 0x5f, 0x41, 0x4e, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x44, 0x45, 0x56, 0x49,
	0x43, 0x45, 0x10, 0x0b, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4d, 0x5f, 0x46, 0x4f, 0x52, 0x42, 0x49,
	0x44, 0x44, 0x45, 0x4e, 0x10, 0x0c, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x4f, 0x4f, 0x5f, 0x4d, 0x41,
	0x4e, 0x59, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x53, 0x10, 0x0d, 0x12, 0x12, 0x0a, 0x0e,
	0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x0e,
	0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4d, 0x55, 0x54, 0x45, 0x44, 0x10, 0x0f,
	0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x5f, 0x44, 0x49, 0x53, 0x41,
	0x42, 0x4c, 0x45, 0x10, 0x10, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54,
	0x5f, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x11, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x45, 0x43,
	0x52, 0x59, 0x50, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x12, 0x12, 0x1e,
	0x0a, 0x1a, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4e,
	0x49, 0x45, 0x44, 0x5f, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x13, 0x12, 0x14,
	0x0a, 0x10, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47,
	0x45, 0x44, 0x10, 0x14, 0x22, 0x2a, 0x0a, 0x0c, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0c, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x12, 0x0c, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x22, 0xd8, 0x08, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2d,
	0x0a, 0x07, 0x6f, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1c, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x12, 0x37,
	0x0a, 0x0c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x73,
	0x69, 0x67, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x12, 0x39, 0x0a, 0x0d, 0x63, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x65, 0x61, 0x73,
	0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0b, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d,
	0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x13, 0x0a, 0x0b,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x12, 0x17, 0x0a, 0x0f, 0x69, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x5f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x12, 0x10, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x12, 0x13, 0x0a, 0x0b,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x12, 0x10, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x12, 0x0c, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x12, 0x0e, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x09, 0x12, 0x11, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x09, 0x12, 0x16, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x12, 0x12, 0x0a, 0x0a,
	0x61, 0x75, 0x74, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0c,
	0x12, 0x17, 0x0a, 0x0f, 0x6f, 0x73, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0d, 0x12, 0x12, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x12, 0x0e, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x12, 0x42, 0x0a,
	0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x16, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x22, 0x2e,
	0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x4c, 0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x63, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x17, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0f, 0x0a, 0x07, 0x6e, 0x74, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0c,
	0x22, 0x82, 0x01, 0x0a, 0x06, 0x4f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4f,
	0x53, 0x5f, 0x49, 0x4f, 0x53, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x53, 0x5f, 0x41, 0x4e,
	0x44, 0x52, 0x4f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x53, 0x5f, 0x4c, 0x49,
	0x4e, 0x55, 0x58, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x53, 0x5f, 0x4f, 0x53, 0x58, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x53, 0x5f, 0x57, 0x49, 0x4e, 0x10, 0x04, 0x12, 0x0d, 0x0a,
	0x09, 0x4f, 0x53, 0x5f, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a,
	0x4f, 0x53, 0x5f, 0x48, 0x41, 0x52, 0x4d, 0x4f, 0x4e, 0x59, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05,
	0x4f, 0x53, 0x5f, 0x47, 0x4f, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x53, 0x5f, 0x4f, 0x54,
	0x48, 0x45, 0x52, 0x10, 0x10, 0x22, 0x73, 0x0a, 0x0b, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52,
	0x4b, 0x5f, 0x57, 0x49, 0x46, 0x49, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x45, 0x54, 0x57,
	0x4f, 0x52, 0x4b, 0x5f, 0x34, 0x47, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x45, 0x54, 0x57,
	0x4f, 0x52, 0x4b, 0x5f, 0x33, 0x47, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x45, 0x54, 0x57,
	0x4f, 0x52, 0x4b, 0x5f, 0x32, 0x47, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x45, 0x54, 0x57,
	0x4f, 0x52, 0x4b, 0x5f, 0x57, 0x49, 0x52, 0x45, 0x10, 0x05, 0x22, 0x46, 0x0a, 0x0c, 0x43, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f,
	0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x5a, 0x4c, 0x49, 0x42, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x4c, 0x5a, 0x34,
	0x10, 0x02, 0x22, 0x37, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x4e, 0x4c, 0x59, 0x5f,
	0x55, 0x50, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x4e, 0x4c, 0x59, 0x5f, 0x44, 0x4f, 0x57,
	0x4e, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x42, 0x49, 0x10, 0x02, 0x22, 0x50, 0x0a, 0x06, 0x4c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x12, 0x0e, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x61, 0x73, 0x65,
	0x6d, 0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x66, 0x0a,
	0x0b, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c,
	0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x17,
	0x0a, 0x13, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x5f, 0x41, 0x45, 0x53, 0x5f, 0x31, 0x32,
	0x38, 0x5f, 0x43, 0x42, 0x43, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x4e, 0x43, 0x52, 0x59,
	0x50, 0x54, 0x5f, 0x41, 0x45, 0x53, 0x5f, 0x32, 0x35, 0x36, 0x5f, 0x43, 0x42, 0x43, 0x10, 0x02,
	0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x5f, 0x41, 0x45, 0x53, 0x5f,
	0x47, 0x43, 0x4d, 0x10, 0x03, 0x42, 0x02, 0x48, 0x03,
}

var (
	file_msync_proto_rawDescOnce sync.Once
	file_msync_proto_rawDescData = file_msync_proto_rawDesc
)

func file_msync_proto_rawDescGZIP() []byte {
	file_msync_proto_rawDescOnce.Do(func() {
		file_msync_proto_rawDescData = protoimpl.X.CompressGZIP(file_msync_proto_rawDescData)
	})
	return file_msync_proto_rawDescData
}

var file_msync_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_msync_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_msync_proto_goTypes = []interface{}{
	(EncryptType)(0),                 // 0: easemob.pb.EncryptType
	(MSync_Version)(0),               // 1: easemob.pb.MSync.Version
	(MSync_Command)(0),               // 2: easemob.pb.MSync.Command
	(Meta_NameSpace)(0),              // 3: easemob.pb.Meta.NameSpace
	(Meta_RouteType)(0),              // 4: easemob.pb.Meta.RouteType
	(Status_ErrorCode)(0),            // 5: easemob.pb.Status.ErrorCode
	(Provision_OsType)(0),            // 6: easemob.pb.Provision.OsType
	(Provision_NetworkType)(0),       // 7: easemob.pb.Provision.NetworkType
	(Provision_CompressType)(0),      // 8: easemob.pb.Provision.CompressType
	(Provision_CompressDirection)(0), // 9: easemob.pb.Provision.CompressDirection
	(*MSync)(nil),                    // 10: easemob.pb.MSync
	(*CommSyncUL)(nil),               // 11: easemob.pb.CommSyncUL
	(*RoamConfig)(nil),               // 12: easemob.pb.RoamConfig
	(*CommSyncDL)(nil),               // 13: easemob.pb.CommSyncDL
	(*CommNotice)(nil),               // 14: easemob.pb.CommNotice
	(*CommUnreadUL)(nil),             // 15: easemob.pb.CommUnreadUL
	(*CommUnreadDL)(nil),             // 16: easemob.pb.CommUnreadDL
	(*MetaQueue)(nil),                // 17: easemob.pb.MetaQueue
	(*Meta)(nil),                     // 18: easemob.pb.Meta
	(*Status)(nil),                   // 19: easemob.pb.Status
	(*RedirectInfo)(nil),             // 20: easemob.pb.RedirectInfo
	(*Provision)(nil),                // 21: easemob.pb.Provision
	(*Logout)(nil),                   // 22: easemob.pb.Logout
	(*JID)(nil),                      // 23: easemob.pb.JID
	(*KeyValue)(nil),                 // 24: easemob.pb.KeyValue
}
var file_msync_proto_depIdxs = []int32{
	1,  // 0: easemob.pb.MSync.version:type_name -> easemob.pb.MSync.Version
	23, // 1: easemob.pb.MSync.guid:type_name -> easemob.pb.JID
	2,  // 2: easemob.pb.MSync.command:type_name -> easemob.pb.MSync.Command
	0,  // 3: easemob.pb.MSync.encrypt_type:type_name -> easemob.pb.EncryptType
	18, // 4: easemob.pb.CommSyncUL.meta:type_name -> easemob.pb.Meta
	23, // 5: easemob.pb.CommSyncUL.queue:type_name -> easemob.pb.JID
	12, // 6: easemob.pb.CommSyncUL.roam_config:type_name -> easemob.pb.RoamConfig
	19, // 7: easemob.pb.CommSyncDL.status:type_name -> easemob.pb.Status
	18, // 8: easemob.pb.CommSyncDL.metas:type_name -> easemob.pb.Meta
	23, // 9: easemob.pb.CommSyncDL.queue:type_name -> easemob.pb.JID
	23, // 10: easemob.pb.CommNotice.queue:type_name -> easemob.pb.JID
	19, // 11: easemob.pb.CommUnreadDL.status:type_name -> easemob.pb.Status
	17, // 12: easemob.pb.CommUnreadDL.unread:type_name -> easemob.pb.MetaQueue
	23, // 13: easemob.pb.MetaQueue.queue:type_name -> easemob.pb.JID
	23, // 14: easemob.pb.Meta.from:type_name -> easemob.pb.JID
	23, // 15: easemob.pb.Meta.to:type_name -> easemob.pb.JID
	3,  // 16: easemob.pb.Meta.ns:type_name -> easemob.pb.Meta.NameSpace
	4,  // 17: easemob.pb.Meta.routetype:type_name -> easemob.pb.Meta.RouteType
	24, // 18: easemob.pb.Meta.ext:type_name -> easemob.pb.KeyValue
	5,  // 19: easemob.pb.Status.error_code:type_name -> easemob.pb.Status.ErrorCode
	20, // 20: easemob.pb.Status.redirect_info:type_name -> easemob.pb.RedirectInfo
	6,  // 21: easemob.pb.Provision.os_type:type_name -> easemob.pb.Provision.OsType
	7,  // 22: easemob.pb.Provision.network_type:type_name -> easemob.pb.Provision.NetworkType
	8,  // 23: easemob.pb.Provision.compress_type:type_name -> easemob.pb.Provision.CompressType
	0,  // 24: easemob.pb.Provision.encrypt_type:type_name -> easemob.pb.EncryptType
	19, // 25: easemob.pb.Provision.status:type_name -> easemob.pb.Status
	8,  // 26: easemob.pb.Provision.protocol_compress_type:type_name -> easemob.pb.Provision.CompressType
	9,  // 27: easemob.pb.Provision.protocol_compress_direction:type_name -> easemob.pb.Provision.CompressDirection
	19, // 28: easemob.pb.Logout.status:type_name -> easemob.pb.Status
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_msync_proto_init() }
func file_msync_proto_init() {
	if File_msync_proto != nil {
		return
	}
	file_jid_proto_init()
	file_keyvalue_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommSyncUL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoamConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommSyncDL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommNotice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommUnreadUL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommUnreadDL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaQueue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedirectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Provision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msync_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Logout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msync_proto_rawDesc,
			NumEnums:      10,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msync_proto_goTypes,
		DependencyIndexes: file_msync_proto_depIdxs,
		EnumInfos:         file_msync_proto_enumTypes,
		MessageInfos:      file_msync_proto_msgTypes,
	}.Build()
	File_msync_proto = out.File
	file_msync_proto_rawDesc = nil
	file_msync_proto_goTypes = nil
	file_msync_proto_depIdxs = nil
}
