// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: statisticsbody.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatisticsBody_Operation int32

const (
	StatisticsBody_INFORMATION                    StatisticsBody_Operation = 0 // sdk send information when login, such as os type, sdk version, login time, etc
	StatisticsBody_USER_REMOVED                   StatisticsBody_Operation = 1 // user was removed from server side while user is online
	StatisticsBody_USER_LOGIN_ANOTHER_DEVICE      StatisticsBody_Operation = 2 // user login on another device
	StatisticsBody_USER_KICKED_BY_CHANGE_PASSWORD StatisticsBody_Operation = 3 // user was kicked by change password
	StatisticsBody_USER_KICKED_BY_OTHER_DEVICE    StatisticsBody_Operation = 4 // user was kicked by other device or console backend
)

// Enum value maps for StatisticsBody_Operation.
var (
	StatisticsBody_Operation_name = map[int32]string{
		0: "INFORMATION",
		1: "USER_REMOVED",
		2: "USER_LOGIN_ANOTHER_DEVICE",
		3: "USER_KICKED_BY_CHANGE_PASSWORD",
		4: "USER_KICKED_BY_OTHER_DEVICE",
	}
	StatisticsBody_Operation_value = map[string]int32{
		"INFORMATION":                    0,
		"USER_REMOVED":                   1,
		"USER_LOGIN_ANOTHER_DEVICE":      2,
		"USER_KICKED_BY_CHANGE_PASSWORD": 3,
		"USER_KICKED_BY_OTHER_DEVICE":    4,
	}
)

func (x StatisticsBody_Operation) Enum() *StatisticsBody_Operation {
	p := new(StatisticsBody_Operation)
	*p = x
	return p
}

func (x StatisticsBody_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatisticsBody_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_statisticsbody_proto_enumTypes[0].Descriptor()
}

func (StatisticsBody_Operation) Type() protoreflect.EnumType {
	return &file_statisticsbody_proto_enumTypes[0]
}

func (x StatisticsBody_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StatisticsBody_Operation) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StatisticsBody_Operation(num)
	return nil
}

// Deprecated: Use StatisticsBody_Operation.Descriptor instead.
func (StatisticsBody_Operation) EnumDescriptor() ([]byte, []int) {
	return file_statisticsbody_proto_rawDescGZIP(), []int{0, 0}
}

type StatisticsBody_OsType int32

const (
	StatisticsBody_OS_IOS     StatisticsBody_OsType = 0
	StatisticsBody_OS_ANDROID StatisticsBody_OsType = 1
	StatisticsBody_OS_LINUX   StatisticsBody_OsType = 2
	StatisticsBody_OS_OSX     StatisticsBody_OsType = 3
	StatisticsBody_OS_WIN     StatisticsBody_OsType = 4
	StatisticsBody_OS_CUSTOM  StatisticsBody_OsType = 5
	StatisticsBody_OS_HARMONY StatisticsBody_OsType = 6
	StatisticsBody_OS_OTHER   StatisticsBody_OsType = 16
)

// Enum value maps for StatisticsBody_OsType.
var (
	StatisticsBody_OsType_name = map[int32]string{
		0:  "OS_IOS",
		1:  "OS_ANDROID",
		2:  "OS_LINUX",
		3:  "OS_OSX",
		4:  "OS_WIN",
		5:  "OS_CUSTOM",
		6:  "OS_HARMONY",
		16: "OS_OTHER",
	}
	StatisticsBody_OsType_value = map[string]int32{
		"OS_IOS":     0,
		"OS_ANDROID": 1,
		"OS_LINUX":   2,
		"OS_OSX":     3,
		"OS_WIN":     4,
		"OS_CUSTOM":  5,
		"OS_HARMONY": 6,
		"OS_OTHER":   16,
	}
)

func (x StatisticsBody_OsType) Enum() *StatisticsBody_OsType {
	p := new(StatisticsBody_OsType)
	*p = x
	return p
}

func (x StatisticsBody_OsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatisticsBody_OsType) Descriptor() protoreflect.EnumDescriptor {
	return file_statisticsbody_proto_enumTypes[1].Descriptor()
}

func (StatisticsBody_OsType) Type() protoreflect.EnumType {
	return &file_statisticsbody_proto_enumTypes[1]
}

func (x StatisticsBody_OsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StatisticsBody_OsType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StatisticsBody_OsType(num)
	return nil
}

// Deprecated: Use StatisticsBody_OsType.Descriptor instead.
func (StatisticsBody_OsType) EnumDescriptor() ([]byte, []int) {
	return file_statisticsbody_proto_rawDescGZIP(), []int{0, 1}
}

type StatisticsBody_NetworkType int32

const (
	StatisticsBody_NETWORK_NONE StatisticsBody_NetworkType = 0
	StatisticsBody_NETWORK_WIFI StatisticsBody_NetworkType = 1
	StatisticsBody_NETWORK_4G   StatisticsBody_NetworkType = 2
	StatisticsBody_NETWORK_3G   StatisticsBody_NetworkType = 3
	StatisticsBody_NETWORK_2G   StatisticsBody_NetworkType = 4
	StatisticsBody_NETWORK_WIRE StatisticsBody_NetworkType = 5
)

// Enum value maps for StatisticsBody_NetworkType.
var (
	StatisticsBody_NetworkType_name = map[int32]string{
		0: "NETWORK_NONE",
		1: "NETWORK_WIFI",
		2: "NETWORK_4G",
		3: "NETWORK_3G",
		4: "NETWORK_2G",
		5: "NETWORK_WIRE",
	}
	StatisticsBody_NetworkType_value = map[string]int32{
		"NETWORK_NONE": 0,
		"NETWORK_WIFI": 1,
		"NETWORK_4G":   2,
		"NETWORK_3G":   3,
		"NETWORK_2G":   4,
		"NETWORK_WIRE": 5,
	}
)

func (x StatisticsBody_NetworkType) Enum() *StatisticsBody_NetworkType {
	p := new(StatisticsBody_NetworkType)
	*p = x
	return p
}

func (x StatisticsBody_NetworkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatisticsBody_NetworkType) Descriptor() protoreflect.EnumDescriptor {
	return file_statisticsbody_proto_enumTypes[2].Descriptor()
}

func (StatisticsBody_NetworkType) Type() protoreflect.EnumType {
	return &file_statisticsbody_proto_enumTypes[2]
}

func (x StatisticsBody_NetworkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StatisticsBody_NetworkType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StatisticsBody_NetworkType(num)
	return nil
}

// Deprecated: Use StatisticsBody_NetworkType.Descriptor instead.
func (StatisticsBody_NetworkType) EnumDescriptor() ([]byte, []int) {
	return file_statisticsbody_proto_rawDescGZIP(), []int{0, 2}
}

type StatisticsBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation         *StatisticsBody_Operation   `protobuf:"varint,1,opt,name=operation,enum=easemob.pb.StatisticsBody_Operation" json:"operation,omitempty"`
	Os                *StatisticsBody_OsType      `protobuf:"varint,2,opt,name=os,enum=easemob.pb.StatisticsBody_OsType" json:"os,omitempty"`
	Version           *string                     `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Network           *StatisticsBody_NetworkType `protobuf:"varint,4,opt,name=network,enum=easemob.pb.StatisticsBody_NetworkType" json:"network,omitempty"`
	ImTime            *uint32                     `protobuf:"varint,5,opt,name=im_time,json=imTime" json:"im_time,omitempty"`
	ChatTime          *uint32                     `protobuf:"varint,6,opt,name=chat_time,json=chatTime" json:"chat_time,omitempty"`
	Location          *string                     `protobuf:"bytes,7,opt,name=location" json:"location,omitempty"`                                              // used for report user location, format: "lonlat:xxx.xxx:xxx, cellid: xxx, wifissid: xxx, mnc: xxx, mcc: xxx"
	ReplaceDeviceName *string                     `protobuf:"bytes,8,opt,name=replace_device_name,json=replaceDeviceName" json:"replace_device_name,omitempty"` //used for notify who kicked you,pass device name default
	SessionId         *string                     `protobuf:"bytes,9,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`                           //connection unique id
	Reason            *string                     `protobuf:"bytes,10,opt,name=reason" json:"reason,omitempty"`                                                 //notify other device reason
}

func (x *StatisticsBody) Reset() {
	*x = StatisticsBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statisticsbody_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsBody) ProtoMessage() {}

func (x *StatisticsBody) ProtoReflect() protoreflect.Message {
	mi := &file_statisticsbody_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsBody.ProtoReflect.Descriptor instead.
func (*StatisticsBody) Descriptor() ([]byte, []int) {
	return file_statisticsbody_proto_rawDescGZIP(), []int{0}
}

func (x *StatisticsBody) GetOperation() StatisticsBody_Operation {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return StatisticsBody_INFORMATION
}

func (x *StatisticsBody) GetOs() StatisticsBody_OsType {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return StatisticsBody_OS_IOS
}

func (x *StatisticsBody) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *StatisticsBody) GetNetwork() StatisticsBody_NetworkType {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return StatisticsBody_NETWORK_NONE
}

func (x *StatisticsBody) GetImTime() uint32 {
	if x != nil && x.ImTime != nil {
		return *x.ImTime
	}
	return 0
}

func (x *StatisticsBody) GetChatTime() uint32 {
	if x != nil && x.ChatTime != nil {
		return *x.ChatTime
	}
	return 0
}

func (x *StatisticsBody) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *StatisticsBody) GetReplaceDeviceName() string {
	if x != nil && x.ReplaceDeviceName != nil {
		return *x.ReplaceDeviceName
	}
	return ""
}

func (x *StatisticsBody) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *StatisticsBody) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

var File_statisticsbody_proto protoreflect.FileDescriptor

var file_statisticsbody_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x6f, 0x64, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e,
	0x70, 0x62, 0x22, 0x9f, 0x06, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x42, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d,
	0x6f, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x42, 0x6f, 0x64, 0x79, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x02, 0x6f, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f, 0x62, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x42, 0x6f, 0x64,
	0x79, 0x2e, 0x4f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x65, 0x61, 0x73, 0x65, 0x6d, 0x6f,
	0x62, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x42,
	0x6f, 0x64, 0x79, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6d, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x6d, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x13, 0x72, 0x65,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x92, 0x01, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e,
	0x5f, 0x41, 0x4e, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x10,
	0x02, 0x12, 0x22, 0x0a, 0x1e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4b, 0x49, 0x43, 0x4b, 0x45, 0x44,
	0x5f, 0x42, 0x59, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57,
	0x4f, 0x52, 0x44, 0x10, 0x03, 0x12, 0x1f, 0x0a, 0x1b, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4b, 0x49,
	0x43, 0x4b, 0x45, 0x44, 0x5f, 0x42, 0x59, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x44, 0x45,
	0x56, 0x49, 0x43, 0x45, 0x10, 0x04, 0x22, 0x77, 0x0a, 0x06, 0x4f, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x53, 0x5f, 0x49, 0x4f, 0x53, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x4f, 0x53, 0x5f, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x4f, 0x53, 0x5f, 0x4c, 0x49, 0x4e, 0x55, 0x58, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x53,
	0x5f, 0x4f, 0x53, 0x58, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x53, 0x5f, 0x57, 0x49, 0x4e,
	0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x53, 0x5f, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x10,
	0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x53, 0x5f, 0x48, 0x41, 0x52, 0x4d, 0x4f, 0x4e, 0x59, 0x10,
	0x06, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x53, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x10, 0x22,
	0x73, 0x0a, 0x0b, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x0c, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x57, 0x49, 0x46, 0x49,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x34, 0x47,
	0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x33, 0x47,
	0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x32, 0x47,
	0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x57, 0x49,
	0x52, 0x45, 0x10, 0x05, 0x42, 0x02, 0x48, 0x03,
}

var (
	file_statisticsbody_proto_rawDescOnce sync.Once
	file_statisticsbody_proto_rawDescData = file_statisticsbody_proto_rawDesc
)

func file_statisticsbody_proto_rawDescGZIP() []byte {
	file_statisticsbody_proto_rawDescOnce.Do(func() {
		file_statisticsbody_proto_rawDescData = protoimpl.X.CompressGZIP(file_statisticsbody_proto_rawDescData)
	})
	return file_statisticsbody_proto_rawDescData
}

var file_statisticsbody_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_statisticsbody_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_statisticsbody_proto_goTypes = []interface{}{
	(StatisticsBody_Operation)(0),   // 0: easemob.pb.StatisticsBody.Operation
	(StatisticsBody_OsType)(0),      // 1: easemob.pb.StatisticsBody.OsType
	(StatisticsBody_NetworkType)(0), // 2: easemob.pb.StatisticsBody.NetworkType
	(*StatisticsBody)(nil),          // 3: easemob.pb.StatisticsBody
}
var file_statisticsbody_proto_depIdxs = []int32{
	0, // 0: easemob.pb.StatisticsBody.operation:type_name -> easemob.pb.StatisticsBody.Operation
	1, // 1: easemob.pb.StatisticsBody.os:type_name -> easemob.pb.StatisticsBody.OsType
	2, // 2: easemob.pb.StatisticsBody.network:type_name -> easemob.pb.StatisticsBody.NetworkType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_statisticsbody_proto_init() }
func file_statisticsbody_proto_init() {
	if File_statisticsbody_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_statisticsbody_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_statisticsbody_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_statisticsbody_proto_goTypes,
		DependencyIndexes: file_statisticsbody_proto_depIdxs,
		EnumInfos:         file_statisticsbody_proto_enumTypes,
		MessageInfos:      file_statisticsbody_proto_msgTypes,
	}.Build()
	File_statisticsbody_proto = out.File
	file_statisticsbody_proto_rawDesc = nil
	file_statisticsbody_proto_goTypes = nil
	file_statisticsbody_proto_depIdxs = nil
}
